import { GeneratorRecipe } from '../types/generator';

const DIVERSE_RECIPES: GeneratorRecipe[] = [
  // BREAKFAST (INDIAN)
  {
    id: "breakfast-poha",
    name: "Poha",
    description: "Light, flattened rice breakfast with spices and veggies",
    category: "Breakfast",
    cuisine: "Indian",
    prepTime: "5 mins",
    cookTime: "10 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 320, protein: "8g", carbs: "55g", fat: "8g", fiber: "5g" },
    ingredients: ["Flattened rice (poha, 1 cup)", "Onion (½ cup, chopped)", "Potato (½ cup, diced)", "Peanuts (2 tbsp)", "Green chilies (1)", "Curry leaves (8-10)", "Turmeric (½ tsp)", "Lemon juice (1 tsp)", "Coriander (2 tbsp)"],
    instructions: ["Rinse poha and set aside.", "Sauté onions, potatoes, peanuts, curry leaves, and green chilies.", "Add turmeric, then mix in poha.", "Cook 2-3 mins, squeeze lemon, garnish with coriander."],
    fitnessBenefits: "Light, easy to digest, complex carbs for energy.",
    ingredientAlternatives: ["Use peas instead of potatoes", "Add grated coconut"],
    imagePrompt: "A plate of poha with onions, potatoes, peanuts, and coriander, Indian breakfast",
    icon: "🍚",
    scores: { proteinScore: 6, healthScore: 9, goalCompatibilityScore: 9, overallScore: 8.5 },
    mealType: "breakfast",
    tags: ["vegetarian", "indian", "quick"]
  },
  {
    id: "breakfast-upma",
    name: "Upma",
    description: "Savory semolina breakfast with vegetables",
    category: "Breakfast",
    cuisine: "Indian",
    prepTime: "5 mins",
    cookTime: "12 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 360, protein: "10g", carbs: "60g", fat: "9g", fiber: "4g" },
    ingredients: ["Semolina (rava, ½ cup)", "Onion (½ cup)", "Carrot (¼ cup, grated)", "Peas (¼ cup)", "Mustard seeds (½ tsp)", "Urad dal (1 tsp)", "Curry leaves (8-10)", "Green chilies (1)"],
    instructions: ["Roast semolina until aromatic.", "Sauté mustard, urad dal, curry leaves, chilies, then veggies.", "Add 1.5 cups water, bring to boil, stir in semolina.", "Cover and cook 2-3 mins."],
    fitnessBenefits: "Balanced carbs, quick energy, veggies for micronutrients.",
    ingredientAlternatives: ["Use fine rava instead of coarse", "Add beans"],
    imagePrompt: "Upma served in a bowl with carrots and peas",
    icon: "🥘",
    scores: { proteinScore: 8, healthScore: 10, goalCompatibilityScore: 9, overallScore: 9 },
    mealType: "breakfast",
    tags: ["vegetarian", "indian", "quick"]
  },
  {
    id: "breakfast-idli",
    name: "Idli with Sambar",
    description: "Steamed rice and urad dal cakes with lentil soup",
    category: "Breakfast",
    cuisine: "Indian (South)",
    prepTime: "10 mins (batter prep)",
    cookTime: "15 mins",
    servings: 3,
    difficulty: "Medium",
    nutrition: { calories: 380, protein: "15g", carbs: "62g", fat: "8g", fiber: "6g" },
    ingredients: ["Idli batter (1 cup)", "Toor dal (¼ cup)", "Tamarind (small lemon size)", "Sambar powder (1 tbsp)", "Mixed veggies (½ cup)", "Ghee (1 tsp)"],
    instructions: ["Steam idlis in idli maker.", "Cook toor dal, make sambar with tamarind and sambar powder.", "Serve idlis with hot sambar and ghee."],
    fitnessBenefits: "Fermented, easy to digest, complete protein from dal and rice.",
    ingredientAlternatives: ["Use ragi idli batter", "Add coconut chutney"],
    imagePrompt: "Steamed idlis served with sambar and chutney on a banana leaf",
    icon: "🫔",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "breakfast",
    tags: ["vegetarian", "indian", "south-indian"]
  },
  {
    id: "breakfast-masala-dosa",
    name: "Masala Dosa",
    description: "Crispy rice and urad dal crepe with potato masala",
    category: "Breakfast",
    cuisine: "Indian (South)",
    prepTime: "10 mins",
    cookTime: "15 mins",
    servings: 1,
    difficulty: "Medium",
    nutrition: { calories: 420, protein: "12g", carbs: "65g", fat: "12g", fiber: "5g" },
    ingredients: ["Dosa batter (½ cup)", "Potato masala (½ cup)", "Onion (½ cup)", "Ghee (1 tsp)"],
    instructions: ["Spread dosa batter on hot tawa, sprinkle ghee.", "Cook until crispy, add potato masala, fold and serve."],
    fitnessBenefits: "Fermented batter, complex carbs, potato for energy.",
    ingredientAlternatives: ["Use ragi dosa", "Make plain dosa"],
    imagePrompt: "Crispy masala dosa with potato filling on a plate",
    icon: "🌮",
    scores: { proteinScore: 7, healthScore: 9, goalCompatibilityScore: 8, overallScore: 8.5 },
    mealType: "breakfast",
    tags: ["vegetarian", "indian", "south-indian"]
  },
  {
    id: "breakfast-egg-bhurji",
    name: "Egg Bhurji with Pav",
    description: "Spicy scrambled eggs with Indian dinner rolls",
    category: "Breakfast",
    cuisine: "Indian",
    prepTime: "5 mins",
    cookTime: "10 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 380, protein: "22g", carbs: "35g", fat: "18g", fiber: "3g" },
    ingredients: ["Eggs (3)", "Onion (½ cup)", "Tomato (½ cup)", "Green chilies (1)", "Pav (2)", "Butter (1 tsp)", "Coriander (2 tbsp)"],
    instructions: ["Sauté onions, chilies, and tomatoes in butter.", "Add eggs and scramble until cooked.", "Serve with pav and coriander."],
    fitnessBenefits: "High protein from eggs, quick and satisfying.",
    ingredientAlternatives: ["Use tofu instead of eggs", "Serve with roti"],
    imagePrompt: "Spicy egg bhurji served with buttered pav",
    icon: "🍳",
    scores: { proteinScore: 10, healthScore: 8, goalCompatibilityScore: 9, overallScore: 9 },
    mealType: "breakfast",
    tags: ["eggetarian", "indian", "high-protein"]
  },
  {
    id: "breakfast-aloo-paratha",
    name: "Aloo Paratha with Curd",
    description: "Stuffed Indian flatbread with yogurt",
    category: "Breakfast",
    cuisine: "Indian (North)",
    prepTime: "10 mins",
    cookTime: "15 mins",
    servings: 1,
    difficulty: "Medium",
    nutrition: { calories: 450, protein: "12g", carbs: "60g", fat: "18g", fiber: "4g" },
    ingredients: ["Whole wheat flour (1 cup)", "Potato (1, boiled)", "Curd (½ cup)", "Ghee (1 tsp)", "Cumin (½ tsp)", "Salt (to taste)"],
    instructions: ["Make dough, stuff with potato masala, roll into paratha.", "Cook on tawa with ghee until golden.", "Serve with curd."],
    fitnessBenefits: "Complex carbs from whole wheat, probiotic curd.",
    ingredientAlternatives: ["Stuff with paneer or gobi", "Use raita instead of plain curd"],
    imagePrompt: "Aloo paratha served with curd and pickle",
    icon: "🥙",
    scores: { proteinScore: 6, healthScore: 8, goalCompatibilityScore: 8, overallScore: 8 },
    mealType: "breakfast",
    tags: ["vegetarian", "indian", "north-indian"]
  },

  // LUNCH (INDIAN)
  {
    id: "lunch-dal-chawal",
    name: "Dal Rice (Dal Chawal)",
    description: "Comfort food: yellow lentils with rice",
    category: "Lunch",
    cuisine: "Indian",
    prepTime: "5 mins",
    cookTime: "25 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 420, protein: "18g", carbs: "70g", fat: "8g", fiber: "7g" },
    ingredients: ["Toor dal (¼ cup)", "Rice (½ cup)", "Onion (½ cup)", "Tomato (½ cup)", "Turmeric (½ tsp)", "Ghee (1 tsp)", "Cumin (½ tsp)"],
    instructions: ["Cook rice and dal separately.", "Make tadka with ghee, cumin, onions, tomatoes, and turmeric.", "Pour tadka over dal, serve with rice."],
    fitnessBenefits: "Complete protein (dal + rice), easy to digest, balanced meal.",
    ingredientAlternatives: ["Use moong dal instead of toor dal", "Add spinach to dal"],
    imagePrompt: "Dal rice served in a bowl with a dollop of ghee",
    icon: "🍚",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "lunch",
    tags: ["vegetarian", "indian", "balanced"]
  },
  {
    id: "lunch-rajma-chawal",
    name: "Rajma Rice",
    description: "Kidney bean curry with steamed rice",
    category: "Lunch",
    cuisine: "Indian (North)",
    prepTime: "10 mins",
    cookTime: "30 mins",
    servings: 1,
    difficulty: "Medium",
    nutrition: { calories: 460, protein: "22g", carbs: "72g", fat: "10g", fiber: "10g" },
    ingredients: ["Rajma (kidney beans, ½ cup)", "Rice (½ cup)", "Onion (½ cup)", "Tomato (1 cup)", "Garam masala (1 tsp)", "Ginger-garlic paste (1 tsp)", "Ghee (1 tsp)"],
    instructions: ["Soak rajma overnight, pressure cook.", "Make gravy with onions, tomatoes, and spices.", "Mix with cooked rajma, serve with rice."],
    fitnessBenefits: "High plant-based protein, fiber from beans.",
    ingredientAlternatives: ["Use chole (chickpeas) instead", "Serve with roti"],
    imagePrompt: "Rajma served with steamed rice and onion rings",
    icon: "🫘",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "lunch",
    tags: ["vegetarian", "indian", "high-protein"]
  },
  {
    id: "lunch-chole-chawal",
    name: "Chole Rice",
    description: "Chickpea curry with rice",
    category: "Lunch",
    cuisine: "Indian (North)",
    prepTime: "10 mins",
    cookTime: "30 mins",
    servings: 1,
    difficulty: "Medium",
    nutrition: { calories: 440, protein: "20g", carbs: "70g", fat: "10g", fiber: "9g" },
    ingredients: ["Chickpeas (½ cup)", "Rice (½ cup)", "Onion (½ cup)", "Tomato (1 cup)", "Chole masala (1 tsp)", "Tea bag (for color)", "Ginger (1 tsp)"],
    instructions: ["Soak and cook chickpeas with tea bag for color.", "Make onion-tomato gravy, add chole masala.", "Mix with chickpeas, serve with rice."],
    fitnessBenefits: "High plant-based protein, fiber from chickpeas.",
    ingredientAlternatives: ["Serve with bhature or roti instead of rice", "Add capsicum"],
    imagePrompt: "Chole curry served with steamed rice",
    icon: "🍲",
    scores: { proteinScore: 9, healthScore: 10, goalCompatibilityScore: 9, overallScore: 9.5 },
    mealType: "lunch",
    tags: ["vegetarian", "indian", "high-protein"]
  },
  {
    id: "lunch-paneer-sabzi-roti",
    name: "Roti with Paneer Sabzi",
    description: "Indian flatbread with cottage cheese curry",
    category: "Lunch",
    cuisine: "Indian",
    prepTime: "10 mins",
    cookTime: "20 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 430, protein: "25g", carbs: "45g", fat: "18g", fiber: "6g" },
    ingredients: ["Whole wheat roti (2)", "Paneer (150g)", "Onion (½ cup)", "Tomato (½ cup)", "Capsicum (½ cup)", "Paneer masala (1 tsp)", "Coriander (2 tbsp)"],
    instructions: ["Sauté onions, tomatoes, and capsicum.", "Add paneer and paneer masala, cook 5 mins.", "Serve with rotis."],
    fitnessBenefits: "High protein from paneer, complex carbs from whole wheat.",
    ingredientAlternatives: ["Use tofu instead of paneer", "Add peas"],
    imagePrompt: "Paneer sabzi served with hot rotis",
    icon: "🧀",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "lunch",
    tags: ["vegetarian", "indian", "high-protein"]
  },
  {
    id: "lunch-bhindi-sabzi-roti",
    name: "Roti with Bhindi Sabzi",
    description: "Indian flatbread with okra stir-fry",
    category: "Lunch",
    cuisine: "Indian",
    prepTime: "10 mins",
    cookTime: "15 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 350, protein: "10g", carbs: "50g", fat: "12g", fiber: "8g" },
    ingredients: ["Whole wheat roti (2)", "Bhindi (okra, 1 cup)", "Onion (½ cup)", "Cumin (½ tsp)", "Turmeric (½ tsp)", "Amchur (dry mango powder, ½ tsp)"],
    instructions: ["Wash and dry bhindi, chop into pieces.", "Sauté with cumin, onions, and spices until crispy.", "Serve with rotis."],
    fitnessBenefits: "High fiber from bhindi, complex carbs.",
    ingredientAlternatives: ["Serve with rice instead", "Add potatoes"],
    imagePrompt: "Crispy bhindi sabzi served with rotis",
    icon: "🥗",
    scores: { proteinScore: 6, healthScore: 10, goalCompatibilityScore: 9, overallScore: 8.5 },
    mealType: "lunch",
    tags: ["vegetarian", "indian", "high-fiber"]
  },
  {
    id: "lunch-aloo-sabzi-roti",
    name: "Roti with Aloo Sabzi",
    description: "Indian flatbread with potato curry",
    category: "Lunch",
    cuisine: "Indian",
    prepTime: "10 mins",
    cookTime: "20 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 380, protein: "8g", carbs: "60g", fat: "12g", fiber: "4g" },
    ingredients: ["Whole wheat roti (2)", "Potatoes (2, medium)", "Onion (½ cup)", "Tomato (½ cup)", "Cumin (½ tsp)", "Turmeric (½ tsp)", "Red chili powder (¼ tsp)"],
    instructions: ["Boil and cube potatoes.", "Make simple onion-tomato gravy, add potatoes.", "Cook 5-10 mins, serve with rotis."],
    fitnessBenefits: "Quick energy from potatoes, complex carbs from roti.",
    ingredientAlternatives: ["Add peas", "Serve with rice"],
    imagePrompt: "Aloo sabzi served with hot rotis",
    icon: "🥔",
    scores: { proteinScore: 5, healthScore: 8, goalCompatibilityScore: 8, overallScore: 7.5 },
    mealType: "lunch",
    tags: ["vegetarian", "indian", "quick"]
  },
  {
    id: "lunch-chicken-curry-rice",
    name: "Chicken Curry with Rice",
    description: "Spicy Indian chicken curry with steamed rice",
    category: "Lunch",
    cuisine: "Indian",
    prepTime: "10 mins",
    cookTime: "30 mins",
    servings: 1,
    difficulty: "Medium",
    nutrition: { calories: 480, protein: "35g", carbs: "45g", fat: "18g", fiber: "4g" },
    ingredients: ["Chicken breast (150g)", "Rice (½ cup)", "Onion (1 cup)", "Tomato (1 cup)", "Ginger-garlic paste (1 tsp)", "Garam masala (1 tsp)", "Turmeric (½ tsp)", "Coriander (2 tbsp)"],
    instructions: ["Marinate chicken with turmeric and salt.", "Make onion-tomato gravy, add chicken, cook until tender.", "Serve with rice."],
    fitnessBenefits: "High lean protein for muscle gain.",
    ingredientAlternatives: ["Serve with roti instead of rice", "Use chicken thighs"],
    imagePrompt: "Chicken curry served with steamed rice",
    icon: "🍗",
    scores: { proteinScore: 10, healthScore: 9, goalCompatibilityScore: 10, overallScore: 9.5 },
    mealType: "lunch",
    tags: ["non-vegetarian", "indian", "high-protein"]
  },
  {
    id: "lunch-chicken-biryani",
    name: "Chicken Biryani",
    description: "Fragrant layered rice dish with chicken",
    category: "Lunch",
    cuisine: "Indian",
    prepTime: "15 mins",
    cookTime: "35 mins",
    servings: 1,
    difficulty: "Hard",
    nutrition: { calories: 550, protein: "32g", carbs: "60g", fat: "20g", fiber: "5g" },
    ingredients: ["Chicken (150g)", "Basmati rice (½ cup)", "Onion (1 cup, fried)", "Biryani masala (1 tsp)", "Mint leaves (½ cup)", "Coriander leaves (½ cup)", "Ghee (1 tsp)"],
    instructions: ["Cook rice until 70% done.", "Marinate and cook chicken with spices.", "Layer rice and chicken, dum cook for 15 mins.", "Serve with raita."],
    fitnessBenefits: "High protein, flavorful, complete meal.",
    ingredientAlternatives: ["Make veg biryani with paneer/veggies", "Use brown rice"],
    imagePrompt: "Chicken biryani in a handi, garnished with fried onions and mint",
    icon: "🍚",
    scores: { proteinScore: 10, healthScore: 8, goalCompatibilityScore: 9, overallScore: 9 },
    mealType: "lunch",
    tags: ["non-vegetarian", "indian", "high-protein"]
  },
  {
    id: "lunch-khichdi",
    name: "Khichdi with Curd",
    description: "One-pot rice and dal dish with yogurt",
    category: "Lunch",
    cuisine: "Indian",
    prepTime: "5 mins",
    cookTime: "20 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 380, protein: "15g", carbs: "60g", fat: "8g", fiber: "6g" },
    ingredients: ["Rice (¼ cup)", "Moong dal (¼ cup)", "Turmeric (½ tsp)", "Ghee (1 tsp)", "Curd (½ cup)", "Cumin (½ tsp)"],
    instructions: ["Cook rice and dal together with turmeric and salt.", "Make tadka with ghee and cumin, pour over khichdi.", "Serve with curd."],
    fitnessBenefits: "Easy to digest, gentle on stomach, balanced protein.",
    ingredientAlternatives: ["Add vegetables to khichdi", "Serve with papad"],
    imagePrompt: "Moong dal khichdi served with curd and ghee",
    icon: "🍲",
    scores: { proteinScore: 9, healthScore: 10, goalCompatibilityScore: 9, overallScore: 9.5 },
    mealType: "lunch",
    tags: ["vegetarian", "indian", "comfort-food"]
  },

  // DINNER (INDIAN)
  {
    id: "dinner-palak-paneer",
    name: "Palak Paneer with Roti",
    description: "Creamy spinach curry with cottage cheese and rotis",
    category: "Dinner",
    cuisine: "Indian",
    prepTime: "10 mins",
    cookTime: "20 mins",
    servings: 1,
    difficulty: "Medium",
    nutrition: { calories: 420, protein: "24g", carbs: "40g", fat: "18g", fiber: "8g" },
    ingredients: ["Palak (spinach, 2 cups)", "Paneer (100g)", "Onion (½ cup)", "Tomato (½ cup)", "Cream (2 tbsp)", "Ginger-garlic (1 tsp)", "Roti (2)"],
    instructions: ["Blanch and puree spinach.", "Make onion-tomato gravy, mix in spinach puree, add paneer cubes.", "Finish with cream, serve with rotis."],
    fitnessBenefits: "High protein, iron from spinach, calcium from paneer.",
    ingredientAlternatives: ["Use tofu instead of paneer", "Serve with rice"],
    imagePrompt: "Palak paneer served with hot rotis",
    icon: "🥬",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "dinner",
    tags: ["vegetarian", "indian", "high-protein"]
  },
  {
    id: "dinner-mixed-veg-sabzi",
    name: "Mixed Vegetable Curry with Roti",
    description: "Assorted veggies in a light curry",
    category: "Dinner",
    cuisine: "Indian",
    prepTime: "10 mins",
    cookTime: "20 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 350, protein: "10g", carbs: "50g", fat: "12g", fiber: "10g" },
    ingredients: ["Mixed veggies (1 cup: carrots, beans, peas, cauliflower)", "Onion (½ cup)", "Tomato (½ cup)", "Garam masala (½ tsp)", "Roti (2)"],
    instructions: ["Cook mixed veggies until tender.", "Make simple onion-tomato gravy, mix in veggies.", "Serve with rotis."],
    fitnessBenefits: "High fiber, lots of micronutrients.",
    ingredientAlternatives: ["Serve with rice instead", "Add paneer"],
    imagePrompt: "Mixed veg curry served with rotis",
    icon: "🥗",
    scores: { proteinScore: 6, healthScore: 10, goalCompatibilityScore: 9, overallScore: 8.5 },
    mealType: "dinner",
    tags: ["vegetarian", "indian", "high-fiber"]
  },
  {
    id: "dinner-fish-curry",
    name: "Fish Curry with Rice",
    description: "Spicy fish curry in coconut or tomato gravy",
    category: "Dinner",
    cuisine: "Indian (Goan/South)",
    prepTime: "10 mins",
    cookTime: "25 mins",
    servings: 1,
    difficulty: "Medium",
    nutrition: { calories: 450, protein: "30g", carbs: "45g", fat: "20g", fiber: "4g" },
    ingredients: ["Fish fillet (150g)", "Rice (½ cup)", "Coconut milk (½ cup)", "Fish masala (1 tsp)", "Curry leaves (10)", "Ginger-garlic (1 tsp)"],
    instructions: ["Marinate fish with turmeric and salt.", "Make coconut milk gravy with spices, add fish, cook gently.", "Serve with rice."],
    fitnessBenefits: "High protein, omega-3 from fish.",
    ingredientAlternatives: ["Use pomfret or kingfish", "Serve with appam instead of rice"],
    imagePrompt: "Fish curry served with steamed rice",
    icon: "🐟",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "dinner",
    tags: ["non-vegetarian", "indian", "high-protein"]
  },
  {
    id: "dinner-grilled-chicken-salad",
    name: "Grilled Chicken with Indian Salad",
    description: "Lean grilled chicken with fresh Indian-style salad",
    category: "Dinner",
    cuisine: "Indian-fusion",
    prepTime: "10 mins",
    cookTime: "20 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 380, protein: "35g", carbs: "15g", fat: "18g", fiber: "4g" },
    ingredients: ["Chicken breast (150g)", "Onion (½ cup, sliced)", "Tomato (1, sliced)", "Cucumber (½ cup)", "Lemon juice (1 tsp)", "Chat masala (½ tsp)", "Olive oil (1 tsp)"],
    instructions: ["Marinate chicken with lemon, salt, pepper, and chat masala.", "Grill or pan-sear until cooked.", "Serve with sliced salad."],
    fitnessBenefits: "Very high protein, low carb for weight loss.",
    ingredientAlternatives: ["Add mint chutney", "Use paneer instead of chicken"],
    imagePrompt: "Grilled chicken breast with fresh onion-tomato-cucumber salad",
    icon: "🥗",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "dinner",
    tags: ["non-vegetarian", "indian", "high-protein", "low-carb"]
  },
  {
    id: "dinner-curd-rice",
    name: "Curd Rice",
    description: "Comforting rice mixed with yogurt",
    category: "Dinner",
    cuisine: "Indian (South)",
    prepTime: "5 mins",
    cookTime: "10 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 320, protein: "10g", carbs: "50g", fat: "8g", fiber: "3g" },
    ingredients: ["Cooked rice (1 cup)", "Curd (1 cup)", "Ghee (1 tsp)", "Mustard seeds (½ tsp)", "Curry leaves (8-10)", "Urad dal (1 tsp)", "Ginger (1 tsp, grated)"],
    instructions: ["Mix rice with curd.", "Make tadka with ghee, mustard, urad dal, curry leaves, and ginger.", "Pour over curd rice, serve cool."],
    fitnessBenefits: "Probiotics, easy to digest, light dinner.",
    ingredientAlternatives: ["Add pomegranate seeds", "Add grated carrot"],
    imagePrompt: "Curd rice garnished with curry leaves and pomegranate",
    icon: "🍚",
    scores: { proteinScore: 6, healthScore: 9, goalCompatibilityScore: 9, overallScore: 8 },
    mealType: "dinner",
    tags: ["vegetarian", "indian", "light"]
  },
  {
    id: "dinner-lemon-rice",
    name: "Lemon Rice",
    description: "Tangy, spiced rice dish",
    category: "Dinner",
    cuisine: "Indian (South)",
    prepTime: "5 mins",
    cookTime: "10 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 360, protein: "8g", carbs: "60g", fat: "10g", fiber: "4g" },
    ingredients: ["Cooked rice (1 cup)", "Lemon juice (2 tbsp)", "Turmeric (½ tsp)", "Mustard seeds (½ tsp)", "Chana dal (1 tsp)", "Curry leaves (10)", "Peanuts (2 tbsp)"],
    instructions: ["Make tadka with mustard, chana dal, curry leaves, and turmeric.", "Mix with rice, add lemon juice and peanuts.", "Serve."],
    fitnessBenefits: "Quick, light, Vitamin C from lemon.",
    ingredientAlternatives: ["Add grated mango", "Add cashews instead of peanuts"],
    imagePrompt: "Lemon rice garnished with peanuts and curry leaves",
    icon: "🍋",
    scores: { proteinScore: 5, healthScore: 8, goalCompatibilityScore: 8, overallScore: 7.5 },
    mealType: "dinner",
    tags: ["vegetarian", "indian", "quick"]
  },

  // SNACKS (INDIAN)
  {
    id: "snack-roasted-chana",
    name: "Roasted Chana with Jaggery",
    description: "Roasted gram with a piece of jaggery",
    category: "Snack",
    cuisine: "Indian",
    prepTime: "2 mins",
    cookTime: "0 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 200, protein: "10g", carbs: "30g", fat: "6g", fiber: "5g" },
    ingredients: ["Roasted chana (1/3 cup)", "Jaggery (small piece, 10g)"],
    instructions: ["Eat roasted chana with a small piece of jaggery."],
    fitnessBenefits: "High plant-based protein, quick energy.",
    ingredientAlternatives: ["Add a few peanuts", "Use gur chana mix"],
    imagePrompt: "Roasted chana and a piece of jaggery in a small bowl",
    icon: "🫘",
    scores: { proteinScore: 9, healthScore: 9, goalCompatibilityScore: 8, overallScore: 8.5 },
    mealType: "snack",
    tags: ["vegetarian", "indian", "quick"]
  },
  {
    id: "snack-fruit-chaat",
    name: "Fruit Salad with Chaat Masala",
    description: "Fresh fruit with Indian spice mix",
    category: "Snack",
    cuisine: "Indian",
    prepTime: "5 mins",
    cookTime: "0 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 180, protein: "2g", carbs: "40g", fat: "1g", fiber: "6g" },
    ingredients: ["Mixed fruits (1 cup: banana, apple, orange, pomegranate)", "Chaat masala (½ tsp)", "Lemon juice (1 tsp)"],
    instructions: ["Chop fruits, sprinkle chaat masala and lemon juice.", "Mix and serve."],
    fitnessBenefits: "High fiber, vitamins, natural sugars.",
    ingredientAlternatives: ["Add grapes or papaya", "Add a pinch of black salt"],
    imagePrompt: "Fresh fruit salad sprinkled with chaat masala",
    icon: "🍎",
    scores: { proteinScore: 2, healthScore: 10, goalCompatibilityScore: 9, overallScore: 8 },
    mealType: "snack",
    tags: ["vegetarian", "indian", "no-cook"]
  },
  {
    id: "snack-sprouted-moong-salad",
    name: "Sprouted Moong Salad",
    description: "Protein-rich sprouted moong bean salad",
    category: "Snack",
    cuisine: "Indian",
    prepTime: "5 mins",
    cookTime: "0 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 180, protein: "14g", carbs: "25g", fat: "4g", fiber: "8g" },
    ingredients: ["Sprouted moong (½ cup)", "Onion (¼ cup)", "Tomato (¼ cup)", "Cucumber (¼ cup)", "Lemon juice (1 tsp)", "Chat masala (½ tsp)", "Coriander (1 tbsp)"],
    instructions: ["Mix sprouted moong with chopped veggies.", "Add lemon juice, chat masala, and coriander."],
    fitnessBenefits: "Very high plant-based protein, high fiber.",
    ingredientAlternatives: ["Add sprouts of chana or matki", "Add sev on top"],
    imagePrompt: "Sprouted moong salad with onions, tomatoes, and coriander",
    icon: "🥗",
    scores: { proteinScore: 10, healthScore: 10, goalCompatibilityScore: 10, overallScore: 10 },
    mealType: "snack",
    tags: ["vegetarian", "indian", "high-protein", "vegan"]
  },
  {
    id: "snack-dry-fruits",
    name: "Dry Fruits and Nuts",
    description: "Mixed almonds, walnuts, cashews, raisins",
    category: "Snack",
    cuisine: "Indian",
    prepTime: "2 mins",
    cookTime: "0 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 280, protein: "8g", carbs: "20g", fat: "20g", fiber: "4g" },
    ingredients: ["Almonds (5)", "Walnuts (2 halves)", "Cashews (5)", "Raisins (10)"],
    instructions: ["Mix and eat as a snack."],
    fitnessBenefits: "Healthy fats, protein, micronutrients.",
    ingredientAlternatives: ["Add pistachios or dates", "Use a small handful"],
    imagePrompt: "A small bowl of mixed dry fruits and nuts",
    icon: "🥜",
    scores: { proteinScore: 6, healthScore: 9, goalCompatibilityScore: 8, overallScore: 8 },
    mealType: "snack",
    tags: ["vegetarian", "indian", "quick"]
  },
  {
    id: "snack-chaas",
    name: "Buttermilk (Chaas)",
    description: "Spiced yogurt drink",
    category: "Snack",
    cuisine: "Indian",
    prepTime: "3 mins",
    cookTime: "0 mins",
    servings: 1,
    difficulty: "Easy",
    nutrition: { calories: 100, protein: "6g", carbs: "12g", fat: "3g", fiber: "0g" },
    ingredients: ["Curd (½ cup)", "Water (½ cup)", "Roasted cumin powder (½ tsp)", "Salt (pinch)", "Mint leaves (5-6)"],
    instructions: ["Blend curd with water, cumin, salt, and mint.", "Serve cool."],
    fitnessBenefits: "Probiotics, hydration, aids digestion.",
    ingredientAlternatives: ["Add a pinch of asafoetida", "Make masala chaas"],
    imagePrompt: "A glass of spiced buttermilk (chaas) garnished with mint",
    icon: "🥤",
    scores: { proteinScore: 7, healthScore: 10, goalCompatibilityScore: 9, overallScore: 9 },
    mealType: "snack",
    tags: ["vegetarian", "indian", "drink"]
  }
];

export function getDiverseRecipe(mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack', usedNames: string[], goals: string = 'maintenance'): GeneratorRecipe {
  let candidates = DIVERSE_RECIPES.filter(r => 
    r.mealType === mealType && !usedNames.includes(r.name)
  );
  
  // Fallback if no unused candidates
  if (candidates.length === 0) {
    candidates = DIVERSE_RECIPES.filter(r => r.mealType === mealType);
  }
  
  // Pick random
  return candidates[Math.floor(Math.random() * candidates.length)];
}

export function getFreeAiRecipe(ingredients: string, goal: string): GeneratorRecipe {
  const used: string[] = [];
  return getDiverseRecipe('lunch', used, goal);
}
